export const LIFE_TOOLS=[
  {name:'read_life',description:'Read the signed-in account’s private Nexus Life: priorities, pillar activities, Life reminders, confirmed actual time, self-reported energy, reflections, and links. Life is its own product; never import ordinary Nex projects without the user choosing to link. Planned time is not evidence an activity happened. Unknown experience is not failure. Energy ratings show reported patterns, not medical findings or causal proof.',input_schema:{type:'object',properties:{}}},
  {name:'manage_life',description:'Help the user design and reflect on Life. For a new or edited activity/reminder, call preview, show the plan and conflicts, then save the returned item with its exact baseline and destination life or linked after the user chooses. life keeps it private to Life and removes any old Nex link; linked updates one stable Nex Schedule or Reminders record and refuses conflicts. Never move fixed commitments to make room without a separate explicit approval. Profile and check_in store only user-supplied priorities, experience, actual times, energy, and memories; never invent ratings or confirmed experience. Reminder records may also carry starts_at/ends_at to reserve Life calendar time; linking reserves the same interval through Nex Reminders. Memory attachments currently use HTTPS links. Delete removes the item and its Nex link, only on an explicit request. Use relevant clickable choices and short optional questions; do not pressure users to optimize every minute.',input_schema:{type:'object',properties:{
    action:{type:'string',enum:['profile','preview','save','check_in','delete']},id:{type:'string'},kind:{type:'string',enum:['activity','reminder']},title:{type:'string'},pillar:{type:'string',enum:['work','sleep','social','health','personal']},
    starts_at:{type:'string'},ends_at:{type:'string'},due_date:{type:['string','null']},due_at:{type:['string','null']},notes:{type:'string'},person:{type:'string'},place:{type:'string'},protected:{type:'boolean'},
    focus:{type:'array',items:{type:'string',enum:['work','sleep','social','health','personal']}},goals:{type:'string'},
    destination:{type:'string',enum:['life','linked']},baseline:{type:'string'},created_at:{type:'number'},updated_at:{type:'number'},
    outcome:{type:'string',enum:['unknown','happened','missed']},actual_starts_at:{type:['string','null']},actual_ends_at:{type:['string','null']},use_planned_times:{type:'boolean'},energy:{type:['integer','null'],minimum:1,maximum:5},reflection:{type:'string'},memory_url:{type:'string'},status:{type:'string',enum:['planned','done']},
  },required:['action']}},
];
