// /lib/nex/tools/pipeline.js
// Handoff Gateway + tunneled-pipeline tool schemas, moved byte-for-byte out
// of lib/nexBrain.js. Schemas only — no dispatch, no logic change.
// These six were contiguous in TOOLS and are spread back at the exact same
// position, so the effective tool order is unchanged.

export const PIPELINE_TOOLS = [
  { name:'prepare_build_handoff',description:'Create a compact context packet only when Justin explicitly asks Nex to hand work to another agent or start a team/pipeline workflow. Never call this merely because a request contains a build verb or has multiple steps. Nex remains the lead and should perform ordinary work directly.',input_schema:{type:'object',properties:{goal:{type:'string'},owner:{type:'string'},repo:{type:'string'},paths:{type:'array',items:{type:'string'}},branch:{type:'string'},acceptance_criteria:{type:'array',items:{type:'string'}}},required:['goal','owner','repo']} },
  { name:'return_handoff_result',description:'Return a builder or reviewer result and evidence to a Handoff Gateway packet.',input_schema:{type:'object',properties:{handoff_id:{type:'string'},summary:{type:'string'},evidence:{type:'array',items:{type:'string'}}},required:['handoff_id','summary']} },
  { name:'start_tunneled_pipeline',description:'Create the real multi-pipe build flow for a large request: one layout/function lane and one design lane start as separate Board tasks; the reviewer/QA task is locked until both return evidence; only a passing review returns one final package to Nex. This coordinates scoped work only and does not merge or deploy.',input_schema:{type:'object',properties:{goal:{type:'string'},owner:{type:'string'},repo:{type:'string'},branch:{type:'string'},acceptance_criteria:{type:'array',items:{type:'string'}},layout_agent:{type:'string'},design_agent:{type:'string'},reviewer_agent:{type:'string'}},required:['goal','owner','repo']} },
  { name:'submit_pipeline_lane_result',description:'Record one completed layout/function or design lane result with evidence. When both lane results are present, this automatically creates the mandatory reviewer/QA Board task.',input_schema:{type:'object',properties:{pipeline_id:{type:'string'},lane:{type:'string',enum:['layout','design']},summary:{type:'string'},evidence:{type:'array',items:{type:'string'}}},required:['pipeline_id','lane','summary']} },
  { name:'submit_pipeline_review',description:'Record the mandatory reviewer/QA decision. A pass produces the single ready-for-Nex package; needs_changes keeps the pipeline out of ready state and records the required corrections.',input_schema:{type:'object',properties:{pipeline_id:{type:'string'},decision:{type:'string',enum:['pass','needs_changes']},summary:{type:'string'},evidence:{type:'array',items:{type:'string'}},corrections:{type:'array',items:{type:'string'}}},required:['pipeline_id','decision','summary']} },
  { name:'get_tunneled_pipeline',description:'Read one tunneled pipeline run, including its lane tasks, evidence, reviewer decision, and final Nex handoff when ready.',input_schema:{type:'object',properties:{pipeline_id:{type:'string'}},required:['pipeline_id']} },
];
